### ISSUE TITLE
Support for remove()

### ISSUE THREAD

**Issue by adipascu** [davecom/SwiftPriorityQueue#7]

**Comment by davecom** [comment]
Hi @adi1133,
There is already a `pop()` method. Do you mean a method that pops but does not return a value? What is the use case for having it instead of just ignoring the return value of `pop()`?

**Comment by adipascu** [comment]
I need to update the position of an item. In java I remove and push back the item. My issue can be solved by a remove or update method that takes in a specific item.

**Comment by davecom** [comment]
@adi1133 
I have added these methods to the latest commit. Check it out and perhaps add additional unit tests. Thanks.
